name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make -j
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
